### PR TITLE
added support for ligatures

### PR DESCRIPTION
**Pull request by rodrigoddalmeida**
This adds support to ligatures (`|>` and `->`)

Related: #27 #17

### CODE REVIEW

**Comment by keathley** [comment]
This is great thanks!

**Comment by rodrigoddalmeida** [comment]
@keathley I might want to merge this as well (?). :)

**Comment by keathley** [comment]
It is :+1: https://github.com/lucasmazza/language-elixir/commit/cb1b3ad2e66a3327e0a446495fccc9e48e297090

**Comment by rodrigoddalmeida** [comment]
Alright! Thanks! :+1:

**Pull request closed without merging**
